export const DATA_FROM_FORM_BLOCKS = 'DATA_FROM_FORM_BLOCKS';
export const DATA_FROM_FORM_INPUT = 'DATA_FROM_FORM_INPUT';
export const REMOVE_CONFIG = 'REMOVE_CONFIG';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';